apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - pvc-state.yaml
  - configmap-config.yaml
  - configmap-skills.yaml
  - hermes-agent-secrets.sops.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - prometheusrule.yaml
